title: 'Latinxs in Tech'
email: organizers@techqueria.org
description: "Calling all latinxs in tech! Whether you just got here last week or your family is been in the country for decades, we have a lot to share and be proud of. Come share your experiences with the community\n"
baseurl: ""
url: 'https://techqueria.org'
enforce_ssl: techqueria.org
twitter_username: techqueriasf
github_username: techqueria
dest: docs
longname: 'Latinxs in Tech'
github: techqueria
twitter: techqueriasf
